FROM nginx:alpine

COPY nginx/nginx.conf /etc/nginx/nginx.conf

COPY nginx/ssl/ /etc/nginx/ssl/

COPY nginx/.well-known/ /etc/nginx/.well-known/
COPY nginx/.cache/ /var/cache/nginx/

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
